# Generated by Django 5.1.2 on 2024-11-21 01:54

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employes',
            fields=[
                ('employes_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employes_name', models.CharField(max_length=30, validators=[django.core.validators.MaxLengthValidator(30)], verbose_name='名前')),
                ('employes_email', models.EmailField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50)], verbose_name='メールアドレス')),
                ('employes_password', models.CharField(max_length=20, validators=[django.core.validators.MaxLengthValidator(20)], verbose_name='パスワード')),
                ('employes_status', models.CharField(max_length=10, validators=[django.core.validators.MaxLengthValidator(10)], verbose_name='アカウントステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
    ]
