# Generated by Django 4.2.6 on 2024-11-19 01:23

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='名前')),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.MaxLengthValidator(12)], verbose_name='電話番号')),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.MaxLengthValidator(50)], verbose_name='メールアドレス')),
                ('password', models.CharField(max_length=128, validators=[django.core.validators.MaxLengthValidator(128)], verbose_name='パスワード')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
    ]
