# Generated by Django 5.1.2 on 2024-11-08 04:55

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='名前')),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.MaxLengthValidator(12)], verbose_name='電話番号')),
                ('email', models.EmailField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50)], verbose_name='メールアドレス')),
                ('password', models.CharField(max_length=128, validators=[django.core.validators.MaxLengthValidator(128)], verbose_name='パスワード')),
                ('address', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50)], verbose_name='住所')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
    ]
