# Generated by Django 4.2.6 on 2025-02-11 08:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_phone', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_address', models.TextField()),
                ('user_cleaning_location', models.CharField(max_length=255)),
                ('user_cleaning_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', '有効'), ('cancelled', 'キャンセル'), ('approved', '許可')], default='active', max_length=10)),
            ],
        ),
    ]
