# Generated by Django 5.1.2 on 2024-11-21 01:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=30, verbose_name='名前')),
                ('admin_email', models.EmailField(max_length=50, verbose_name='メールアドレス')),
                ('admin_password', models.CharField(max_length=20, verbose_name='パスワード')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
    ]
