# Generated by Django 4.2.6 on 2024-11-11 01:06

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_contactus',
            fields=[
                ('contactus_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contactus_name', models.CharField(max_length=15, validators=[django.core.validators.MaxLengthValidator(15)], verbose_name='名前')),
                ('contactus_email', models.EmailField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50)], verbose_name='メールアドレス')),
                ('contactus_message', models.TextField(max_length=500, validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='メッセージ内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
    ]
