# Generated by Django 4.2.6 on 2024-11-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reservation',
            name='user_phone',
            field=models.CharField(max_length=12, verbose_name='電話番号'),
        ),
    ]
