# Generated by Django 4.2.6 on 2025-02-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreservation',
            name='status',
            field=models.CharField(choices=[('active', '許可'), ('canceled', 'キャンセル'), ('pending_active', '許可待ち')], default='pending_active', max_length=15, verbose_name='ステータス'),
        ),
    ]
