# Generated by Django 4.2.6 on 2025-02-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_userreservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreservation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('pending_active', 'Pending_Active')], default='pending_active', max_length=15, verbose_name='ステータス'),
        ),
    ]
